# Website
url: https://strappazzon.github.io/td2-map-brooklyn
baseurl: /

meta:
  name: The Division 2 Map
  title: Brooklyn
  description: "Interactive map of The Division 2's Brooklyn DLC"
  keywords: ["the division 2", "interactive", "map", "brooklyn"]
  author: Strappazzon

# Excluded files, folders
exclude:
  - Gemfile
  - LICENSE*
  - SUPPORT.md

# CSS
sass:
  sass_dir: assets/sass
  sourcemap: development
  style: compressed

# jekyll-autoprefixer-v2 plugin
autoprefixer:
  browsers:
    - last 2 versions
    - not dead
    - firefox esr
    - chrome 126
  only_production: true

# jekyll-terser plugin
jekyll-terser:
  only_production: true
