name: Bug Report
description: Create a new ticket for a bug.

labels:
  - "bug"
assignees:
  - Strappazzon

body:
  - type: markdown
    attributes:
      value: >2
        **NOTE:** If you are reporting a security issue, read the
        [Security Policy](https://github.com/Strappazzon/.github/blob/-/SECURITY.md) instead of opening a public ticket.


  - type: markdown
    attributes:
      value: Read the [Contributing Guidelines](https://github.com/Strappazzon/td2-map-brooklyn/blob/-/.github/CONTRIBUTING.md) before opening a ticket.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a description of the issue.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide a screenshot showing the issue.
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser Version
      description: The browser and version that you are using to access the website.
      placeholder: Firefox 138.0.3
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: The operating system you are using to access the website.
      placeholder: Windows 11
    validations:
      required: false

  - type: textarea
    id: fix
    attributes:
      label: Proposed Fix
      description: Explain how you think this should be fixed.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Making sure you have read everything before submitting your ticket.
      options:
        - label: I agree to follow the [Code of Conduct](https://github.com/Strappazzon/.github/blob/-/CODE_OF_CONDUCT.md).
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/Strappazzon/td2-map-brooklyn/blob/-/.github/CONTRIBUTING.md).
          required: true
        - label: I have read the [Support Policy](https://github.com/Strappazzon/td2-map-brooklyn/blob/master/SUPPORT.md#support-policy).
          required: true
